export const categories = [
  { id: "Dendrobium", name: "Dendrobium" },
  { id: "Brassavola", name: "Brassavola" },
  { id: "Cattleya", name: "Cattleya" },
  { id: "Phalaenopsis", name: "Phalaenopsis" },
  { id: "Vanda", name: "Vanda" },
  { id: "Cymbidium", name: "Cymbidium" },
  { id: "Oncidium", name: "Oncidium" },
  { id: "Paphiopedilum", name: "Paphiopedilum" },
  { id: "Zygopetalum", name: "Zygopetalum" },
  { id: "Maxillaria", name: "Maxillaria" },
  { id: "Brassia", name: "Brassia" },
  { id: "Laelia", name: "Laelia" },
  { id: "Bulbophyllum", name: "Bulbophyllum" },
  { id: "Coelogyne", name: "Coelogyne" },
  { id: "Miltonia", name: "Miltonia" },
  { id: "Phragmipedium", name: "Phragmipedium" },
];
